<?php  echo $this->doctype()?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Description</title>
  <?php echo $this->headLink()->appendStylesheet('/css/global.css') ?>
</head>
<body>
<table>
<tr>
    <p>Job Title:</p>
    <div align="left" style="border:1px solid red">
    <?php echo $this->escape($this->job['title']);?>
     </div>
    <p>Short Description:</p>
     <div align="left" style="border:1px solid red">
     <?php echo $this->escape($this->job['shortd']);?>
     </div>
    <p>Long Description:</p>
    <div align="left" style="border:1px solid red">
     <?php echo $this->escape($this->job['longd']);?>
     </div>
    <p>Experience/Skills Required:</p>
    <div align="left" style="border:1px solid red">
     <?php echo $this->escape($this->job['exp']);?>
     </div>
    <p>Job Location:</p>
    <div align="left" style="border:1px solid red">
     <?php echo $this->escape($this->job['location']);?>
     </div>
    
</tr>
</table>
    </body>
</html>